

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/join2
    username: sa
    password:
    driver-class-name: org.h2.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username: dogtemptt@gmail.com
    password: qorwns78
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace