
spring:
  datasource:
    url: jdbc:h2:my-h2/~:/dog

    username: sa
    password:
    driver-class-name: org.h2.Driver


  #  // jdbc:h2:tcp://localhost/~/join2
  mail:
    host: smtp.gmail.com
    port: 587
    username: dogtemptt@gmail.com
    password: qorwns78
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: true


  mvc:
    resources:
      mapping: /images/**
      location: /static/images/

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    context-path: /